site_name: SCALE Medicaid Lab Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Onboarding:
    - New Member Onboarding: onboarding/new_member_onboarding.md
    - New Member Tips: onboarding/new_member_tips.md
    - Data and Systems Overview: onboarding/data_and_systems.md
  - Data Science Practices:
    - Project Organization: data_science/project_organization.md
    - Coding Conventions: data_science/coding_conventions.md
    - Open Data Resources: data_science/open_data_resources.md
    - Parallelization: data_science/parallelization.md
    - Virtual Environments:
      - Overview: data_science/venv/venv_overview.md
      - Python Virtual Environments: data_science/venv/py_venv.md
      - R Virtual Environments: data_science/venv/r_venv.md
  - State Medicaid Data:
    - State Medicaid Data Overview: state_data/state_medicaid_data.md
    - Working on the Yale Server: state_data/server_connect.md
  - T-MSIS:
    - T-MSIS Overview: tmsis/tmsis_medicaid_data.md
    - Working on Milgram: tmsis/tmsis_getting_started.md
    - Collaborating on Code: tmsis/tmsis_code_collab.md
    - R & Python Environments: tmsis/tmsis_environments.md
    - Vignettes:
      - Working with File Sizes: tmsis/vignettes/working_with_file_sizes.md
      - Identifying Enrollment & Duals: tmsis/vignettes/enrollment.md
      - Identifying ED Visits: tmsis/vignettes/identifying_ED_visits.md
      - Identifying Providers and Facilities: tmsis/vignettes/providers.md
      - Working in R: tmsis/vignettes/working_in_R.md
  - CT DSS Embedded Materials:
    - Guidebook: embedding/guidebook.md
    - Onboarding: embedding/onboarding.md
    - Coding Best Practices: embedding/coding_best_practices.md
  - Research Areas: research_areas.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
