site_name: SCALE Medicaid Lab Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Onboarding:
    - New Member Onboarding: onboarding/new_member_onboarding.md
  - Data Science:
    - Connecting to the Server: data_science/server_connect.md
    - Project Organization: data_science/project_organization.md
    - Virtual Environments: 
      - Overview: data_science/venv/venv_overview.md
      - Python Virtual Environments: data_science/venv/py_venv.md
      - R Virtual Environments: data_science/venv/r_venv.md
    - Coding Conventions: data_science/coding_conventions.md 
    - State Medicaid Data: data_science/state_medicaid_data.md
  - T-MSIS: 
    - T-MSIS Overview: tmsis/tmsis_medicaid_data.md
    - Working on Milgram: tmsis/tmsis_getting_started.md
    - Vignettes:
      - Identifying ED Visits: tmsis/vignettes/identifying_ED_visits.md
  - Project Links: project_links.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js